---
sidebar: sidebar
permalink: index.html
keywords:
summary:
---

= SnapCenter Plug-in for VMware vSphere documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
//
//
//
//

SnapCenter Plug-in for VMware vSphere (SCV) provides fast, space-efficient, crash-consistent, and VM-consistent backup and restore operations for VMs, Datastores, and VMDKs. SCV removes the SnapCenter Server dependency with its 4.2.x release and is packaged as a Linux-based Virtual Appliance (Open Virtual Appliance format).

== Features

* *VM-consistent and crash-consistent data protection operations*
+
For Crash-consistent or VM-consistent backup and restore operations of VMware VMs and Datastores, use this appliance through the plug-in's web client GUI in vCenter. There is no need to deploy SnapCenter Server in this case.

* *Application-consistent (application over VMDK/RDM) data protection operations*
+
For application-consistent backup and restore operations of Oracle, MS-SQL, or Exchange workloads on VMware, you need to use the SnapCenter Server GUI and the appropriate application plug-in in conjunction with SnapCenter Plug-in for VMware vSphere.

* *SnapCenter VMware plug-in is deployed as a virtual appliance in a Linux VM*
+
Although the virtual appliance must be installed as a Linux VM, the SnapCenter VMware plug-in supports both Windows-based and Linux-based vCenters.

* *SnapCenter Plug-in for VMware vSphere supports iSCSI, Fibre Channel, FCoE, VMDK over NFS 3.0 and 4.1, and VMDK over VMFS 5.0 and 6.0*

== Quick links

* link:scpivs44_get_started_overview.html[Get started]
* link:scpivs44_quick_start_overview.html[Quick start]
* link:scpivs44_protect_data_overview.html[Protect Data]
* link:scpivs44_rest_apis_overview.html[REST APIs]
* link:scpivs44_upgrade_overview.html[Upgrade]
* link:scpivs44_migrate_to_the_linux-based_snapcenter_plug-in_for_vmware_vsphere_overview.html[Migrate]

== Related links

* For the latest information about supported versions, see the https://mysupport.netapp.com/matrix/imt.jsp?components=91324;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] (IMT).
* For information about SnapCenter data protection, see the Data Protection Guide for your SnapCenter plug-in in the http://docs.netapp.com/ocsc-43/index.jsp[SnapCenter Documentation Center^].
* For information about supported upgrade and migration paths, see the https://library.netapp.com/ecm/ecm_download_file/ECMLP2873358[SnapCenter Plug-in for VMware vSphere Release Notes^].
