---
sidebar: sidebar
permalink: index.html
keywords:
summary:
---

= SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
//
//
//
//

SnapCenter Plug-in for VMware vSphere (SCV) provides fast, space-efficient, crash-consistent, and VM-consistent backup and restore operations for VMs, Datastores, and VMDKs. SCV removes the SnapCenter Server dependency with its 4.2.x release and is packaged as a Linux-based Virtual Appliance (Open Virtual Appliance format).

== Features

* *VM-consistent and crash-consistent data protection operations*
+
For Crash-consistent or VM-consistent backup and restore operations of VMware VMs and Datastores, use this appliance through the plug-in's web client GUI in vCenter. There is no need to deploy SnapCenter Server in this case.

* *Application-consistent (application over VMDK/RDM) data protection operations*
+
For application-consistent backup and restore operations of Oracle, MS-SQL, or Exchange workloads on VMware, you need to use the SnapCenter Server GUI and the appropriate application plug-in in conjunction with SnapCenter Plug-in for VMware vSphere.

* *SnapCenter VMware plug-in is deployed as a virtual appliance in a Linux VM*
+
Although the virtual appliance must be installed as a Linux VM, the SnapCenter VMware plug-in supports both Windows-based and Linux-based vCenters.

* *SnapCenter Plug-in for VMware vSphere supports iSCSI, Fibre Channel, FCoE, VMDK over NFS 3.0 and 4.1, and VMDK over VMFS 5.0 and 6.0*

== Support

https://www.netapp.com/data-protection/backup-recovery/snapcenter-backup-management/documentation/[Resources^]

https://mysupport.netapp.com/matrix/imt.jsp?components=91324;&solution=1517&isHWU&src=IMT[Supported versions^]
