---
settings:
  name: SnapCenter Plug-in for VMware vSphere 4.7
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - name: SnapCenter Plug-in for VMware vSphere
      url: /sc-plugin-vmware-vsphere
      version-number: "4.7"
    - name: SnapCenter Plug-in for VMware vSphere
      url: /sc-plugin-vmware-vsphere-46
      version-number: "4.6"
    - name: SnapCenter Plug-in for VMware vSphere
      url: /sc-plugin-vmware-vsphere-45
      version-number: "4.5"

sidebar:
  entries:
    - title: SnapCenter Plug-in for VMware vSphere 4.7 docs
      url: /index.html
    - title: Release notes
      url: /scpivs44_release_notes.html
    - title: Concepts
      entries:
        - title: Product overview
          url: /scpivs44_concepts_overview.html
        - title: Overview of the different SnapCenter GUIs
          url: /scpivs44_overview_of_different_snapcenter_guis.html
        - title: Licensing
          url: /scpivs44_licensing.html
        - title: Role-Based Access Control (RBAC)
          url: /scpivs44_role_based_access_control.html
        - title: Types of RBAC for SnapCenter Plug-in for VMware vSphere users
          url: /scpivs44_types_of_rbac_for_snapcenter_users.html
        - title: ONTAP RBAC features in SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_ontap_rbac_features_in_snapcenter.html
        - title: Predefined roles packaged with SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_predefined_roles_packaged_with_snapcenter.html
        - title: How to configure ONTAP RBAC for SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_how_to_configure_ontap_rbac_for_snapcenter_plug-in_for_vmware_vsphere.html
    - title: Get started
      entries:
        - title: Deployment Overview
          url: /scpivs44_get_started_overview.html
        - title: Deployment workflow for new users
          url: scpivs44_deployment_workflow_for_new_users.html
        - title: Deployment workflow for existing users
          url: /scpivs44_deployment_workflow_for_existing_users.html
        - title: Requirements for deploying SCV
          entries:
            - title: Deployment planning and requirements
              url: /scpivs44_deployment_planning_and_requirements.html
            - title: Minimum ONTAP privileges required
              url: /scpivs44_minimum_ontap_privileges_required.html
            - title: Minimum vCenter privileges required
              url: /scpivs44_minimum_vcenter_privileges_required.html
        - title: Download the SnapCenter Plug-in for VMware vSphere OVA (Open Virtual Appliance)
          url: /scpivs44_download_the_snapcenter_plug-in_for_vmware_vsphere_ova_open_virtual_appliance.html
        - title: Deploy SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html
        - title: Post deployment required operations and issues
          url: /scpivs44_post_deployment_required_operations_and_issues.html
        - title: Log in to the SnapCenter VMware vSphere web client
          url: /scpivs44_log_in_to_the_snapcenter_vmware_vsphere_web_client.html
    - title: Quick start
      entries:
        - title: Overview
          url: /scpivs44_quick_start_overview.html
        - title: Download the OVA (Open Virtual Appliance)
          url: /scpivs44_download_the_ova_open_virtual_appliance.html
        - title: Deploy SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html
        - title: Add storage
          url: /scpivs44_add_storage.html
        - title: Create backup policies
          url: /scpivs44_create_backup_policies.html
        - title: Create resource groups
          url: /scpivs44_create_resource_groups.html
    - title: Monitor and report
      entries:
        - title: View status information
          url: /scpivs44_view_status_information.html
        - title: Monitor jobs
          url: /scpivs44_monitor_jobs.html
        - title: Download job logs
          url: /scpivs44_download_job_logs.html
        - title: Access reports
          url: /scpivs44_access_reports.html
        - title: Generate a support bundle from the SnapCenter Plug-in for VMware vSphere GUI
          url: /scpivs44_generate_a_support_bundle_from_the_snapcenter_plug-in_for_vmware_vsphere_gui.html
        - title: Generate a support bundle from the maintenance console
          url: /scpivs44_generate_a_support_bundle_from_the_maintenance_console.html
    - title: Manage storage
      entries:
        - title: Add storage
          url: /scpivs44_add_storage_01.html
        - title: Manage storage VMs - modify, rename, remove
          url: /scpivs44_manage_storage_systems.html
        - title: Modify the configured storage timeout
          url: /scpivs44_modify_storage_timeout.html
    - title: Protect data
      entries:
        - title: Data protection workflow
          url: /scpivs44_protect_data_overview.html
        - title: View backups
          url: /scpivs44_view_vm_and_datastore_backups.html
        - title: Create backup policies
          url: /scpivs44_create_backup_policies_for_vms_and_datastores.html
        - title: Create resource groups
          url: /scpivs44_create_resource_groups_for_vms_and_datastores.html
        - title: Prescripts and postscripts
          url: /scpivs44_prescripts_and_postscripts.html
        - title: Add a single VM or datastore to a resource group
          url: /scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html
        - title: Add multiple VMs and datastores to a resource group
          url: /scpivs44_add_multiple_vms_and_datastores_to_a_resource_group.html
        - title: Back up resource groups on demand
          url: /scpivs44_back_up_resource_groups_on_demand.html
        - title: Back up the MySQL database
          url: /scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html
        - title: Manage resource groups - suspend, resume, modify, delete
          url: /scpivs44_manage_resource_groups.html
        - title: Manage policies - detach, modify, delete
          url: /scpivs44_manage_policies.html
        - title: Manage backups - rename, delete
          url: /scpivs44_manage_backups.html
    - title: Mount and unmount datastores
      entries:
        - title: Mount a backup
          url: /scpivs44_mount_a_backup.html
        - title: Unmount a backup
          url: /scpivs44_unmount_a_backup.html
    - title: Restore from backups
      entries:
        - title: Overview
          url: /scpivs44_restore_from_backups_overview.html
        - title: How restore operations are performed
          url: /scpivs44_how_restore_operations_are_performed.html
        - title: Search for backups
          url: /scpivs44_search_for_backups.html
        - title: Restore VMs from backups
          url: /scpivs44_restore_vms_from_backups.html
        - title: Restore deleted VMs from backups
          url: /scpivs44_restore_deleted_vms_from_backups.html
        - title: Restore VMDKs from backups
          url: /scpivs44_restore_vmdks_from_backups.html
        - title: Restore the most recent backup of the MySQL database
          url: /scpivs44_restore_the_most_recent_backup_of_the_mysql_database.html
        - title: Restore a specific backup of the MySQL database
          url: /scpivs44_restore_a_specific_backup_of_the_mysql_database.html
        - title: Attach VMDKs to a VM or vVol VM
          url: /scpivs44_attach_vmdks_to_a_vm.html
        - title: Detach a virtual disk
          url: /scpivs44_detach_a_virtual_disk.html
    - title: Restore guest files and folders
      entries:
        - title: Workflow, prerequisites, and limitations
          url: /scpivs44_restore_guest_files_and_folders_overview.html
        - title: Restore guest files and folders from VMDKs
          url: /scpivs44_restore_guest_files_and_folders_from_vmdks.html
        - title: Set up proxy VMs for restore operations
          url: /scpivs44_set_up_proxy_vms_for_restore_operations.html
        - title: Configure credentials for VM guest file restores
          url: /scpivs44_configure_credentials_for_vm_guest_file_restores.html
        - title: Extend the time of a guest file restore session
          url: /scpivs44_extend_the_time_of_a_guest_file_restore_session.html
        - title: Guest file restore scenarios you might encounter
          url: /scpivs44_guest_file_restore_scenarios_you_might_encounter.html
    - title: Manage SnapCenter Plug-in for VMware vSphere appliance
      entries:
        - title: Restart the VMware vSphere web client service
          url: /scpivs44_restart_the_vmware_vsphere_web_client_service.html
        - title: Access the maintenance console
          url: /scpivs44_access_the_maintenance_console.html
        - title: Modify the SnapCenter VMware Plug-in password from the maintenance console
          url: /scpivs44_modify_plugin_password.html
        - title: Create and import certificates
          url: /scpivs44_create_and_import_certificates.html
        - title: Unregister SnapCenter Plug-in for VMware vSphere from vCenter
          url: /scpivs44_unregister_plugin_from_vcenter.html
        - title: Disable and enable SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_disable_and_enable_plugin.html
        - title: Remove SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_remove_plugin.html
    - title: Manage your configuration
      entries:
        - title: Modify time zones
          url: /scpivs44_modify_the_time_zones.html
        - title: Modify logon credentials
          url: /scpivs44_modify_the_logon_credentials.html
        - title: Modify vCenter logon credentials
          url: /scpivs44_modify_the_vcenter_logon_credentials.html
        - title: Modify network settings
          url: /scpivs44_modify_the_network_settings.html
        - title: Modify configuration default values
          url: /scpivs44_modify_configuration_default_values.html
        - title: Create the scbr.override file
          url: /scpivs44_create_the_scbr_override_file.html
        - title: Configuration properties you can override
          url: /scpivs44_properties_you_can_override.html
        - title: Enable SSH
          url: /scpivs44_enable_ssh.html
    - title: REST APIs
      entries:
        - title: Overview
          url: /scpivs44_rest_apis_overview.html
        - title: Access REST APIs using the Swagger API web page
          url: /scpivs44_access_rest_apis_using_the_swagger_api_web_page.html
        - title: REST API workflows to add and modify storage VMs
          url: /scpivs44_rest_api_workflows__add_and_modify_storage_vms.html
        - title: REST API workflows to create and modify resource groups
          url: /scpivs44_rest_api_workflows__create_and_modify_resource_groups.html
        - title: REST API workflow to back up on demand
          url: /scpivs44_rest_api_workflow__back_up_on_demand.html
        - title: REST API workflow to restore VMs
          url: /scpivs44_rest_api_workflow__restore_vms.html
        - title: REST API workflow to restore deleted VMs
          url: /scpivs44_rest_api_workflow__restore_deleted_vms.html
        - title: REST API workflow to restore VMDKs
          url: /scpivs44_rest_api_workflow__restore_vmdks.html
        - title: REST API workflows to attach and detach VMDKs
          url: /scpivs44_rest_api_workflows__attach_and_detach_vmdks.html
        - title: REST API workflows to mount and unmount datastores
          url: /scpivs44_rest_api_workflows__mount_and_unmount_datastores.html
        - title: REST APIs to download jobs and generate reports
          url: /scpivs44_rest_apis__download_jobs_and_generate_reports.html
        - title: REST APIs workflows to modify built-in schedules
          url: /scpivs44_rest_api_workflows__modify_built-in_schedules.html
        - title: REST API to mark stuck jobs as failed
          url: /scpivs44_rest_apis_fail_stuck_jobs.html
    - title: Upgrade
      entries:
        - title: Upgrade from an earlier release of SnapCenter Plug-in for VMware vSphere
          url: /scpivs44_upgrade.html
        - title: Upgrade to a new patch of the same release
          url: /scpivs44_upgrade_to_a_new_patch.html
        - title: Information not displayed after upgrading to a new patch of the same release
          url: /scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Release Notes
          url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2883356
        - title: Learn about SCV
          url: /scpivs44_concepts_overview.html
        - title: Deployment requirements
          url: /scpivs44_deployment_planning_and_requirements.html
        - title: Quick start
          url: /scpivs44_download_the_ova_open_virtual_appliance.html
    - title: Protect VMs, VMDKs, and datastores
      links:
        - title: Protect your data
          url: /scpivs44_protect_data_overview.html
        - title: Restore from backups
          url: /scpivs44_restore_from_backups_overview.html
        - title: Use REST APIs
          url: /scpivs44_rest_apis_overview.html
        - title: Migrate from Windows-based SCV
          url: /scpivs44_migrate.html
    - title: Blogs & community
      links:
        - title: NetApp blog – SCV
          url: https://blog.netapp.com/tag/snapcenter/
        - title: NetApp community – SCV
          url: https://community.netapp.com/t5/forums/filteredbylabelpage/board-id/backup-and-restore-discussions/label-name/snapcenter
    - title: More resources
      links:
        - title: SnapCenter Software documentation
          url: https://docs.netapp.com/us-en/snapcenter/index.html
        - title: Documentation for earlier versions of SCV
          url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=63240
        - title: NetApp Knowledge Base – SCV
          url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter
