---
sidebar: sidebar
permalink: rename_storage.html
keywords:
summary: 'You can rename the storage using REST API.'
---

= Restore backup of renamed storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When the storage is renamed, restoring the storage and other workflows with the backup taken before the rename fails. You need to take a backup after renaming the storage for the restore operation to work. With the introduction of the rename backup feature, you can use the backup that was taken prior to storage renaming. You need to use REST API operation shown below to enable successful backup restoration.

.Steps

. If you have added the storage connection when a new cluster or SVM is added or updated the storage connection when an SVM is renamed, restart the service to refresh the cache.
+
See KB article: <tbd>
. Create a new backup.
. Use the backup details to find the old and new storage names.
. In the *Backups* screen of the vSphere client, select the backup to see its details.
. Access Swagger from the URL: https://<SCV-IP>:8144/api/swagger-ui/index.html
+
Use the following API to rename the storage:
+
PATCH
/4.1/storage-system
+
Example:
{
  "existingSVM": {
    "name": "string"
  },
  "newSVM": {
    "name": "string"
  }
}
+
Response:
+

{
  "response": {},
  "responseMessage": [
    "string"
  ],
  "statusCode": 0,
  "statusMessage": "string"
}

+
The API validates if the new storage connection exists, creates a job for tracking and audit, and renames storage in the metadata

After running this API you will be able to run all the workflows including the restore operation from the old backup.
