---
sidebar: sidebar
permalink: scpivs44_how_restore_operations_are_performed.html
keywords:
summary: 'For VMFS environments, the SnapCenter Plug-in for VMware vSphere uses clone and mount operations with Storage VMotion to perform restore operations. For NFS environments, the plug-in uses native ONTAP Single File SnapRestore (SFSR) to provide greater efficiency for most restore operations. For vVol VMs, the plug-in uses ONTAP Single File Snapshot Restore and SnapMirror Restore for restore operations.'
---

= How restore operations are performed
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:24.060765
//

For VMFS environments, the SnapCenter Plug-in for VMware vSphere uses clone and mount operations with Storage VMotion to perform restore operations. For NFS environments, the plug-in uses native ONTAP Single File SnapRestore (SFSR) to provide greater efficiency for most restore operations. For vVol VMs, the plug-in uses ONTAP Single File Snapshot Restore (ONTAP SFSR) and SnapMirror Restore for restore operations. The following table lists how restore operations are performed.

|===
|Restore operations |From |Performed using

|VMs and VMDKs
|Primary backups
|NFS environments: ONTAP Single File SnapRestore
VMFS environments: Clone and mount with Storage VMotion
|VMs and VMDKs
|Secondary backups
|NFS environments: ONTAP Single File SnapRestore
VMFS environments: Clone and mount with Storage VMotion
|Deleted VMs and VMDKs
|Primary backups
|NFS environments: ONTAP Single File SnapRestore
VMFS environments: Clone and mount with Storage VMotion
|Deleted VMs and VMDKs
|Secondary backups
|NFS environments: Clone and mount with Storage VMotion
VMFS environments: Clone and mount with Storage VMotion
|VMs and VMDKs
|VM-consistent primary backups
|NFS environments: ONTAP Single File SnapRestore
VMFS environments: Clone and mount with Storage VMotion
|VMs and VMDKs
|VM-consistent secondary backups
|NFS environments: Clone and mount with Storage VMotion
VMFS environments: Clone and mount with Storage VMotion
|vVol VMs
|Crash-consistent primary backups
|ONTAP Single File SnapRestore for all protocols
|vVol VMs
|Crash-consistent secondary backups
|ONTAP SnapMirror Restore for all protocols
|FlexGroup VMs
|Primary backups
a|NFS environments:
* ONTAP Single File SnapRestore if you are using ONTAP Version 9.10.1 and later
* Clone and mount with Storage VMotion on ONTAP previous versions

VMFS environments: Not supported for FlexGroups
|FlexGroup VMs
|Secondary backups
a|NFS environments:

* ONTAP SnapMirror Restore  if you are using ONTAP Version 9.10.1 and later
* Clone and mount with Storage VMotion for ONTAP previous versions

VMFS environments: Not supported for FlexGroups
|===

[NOTE]
You cannot restore a vVol VM after a vVol container rebalance.

Guest file restore operations are performed using clone and mount operations (not Storage VMotion) in both NFS and VMFS environments.

[IMPORTANT]
During a restore operation, you might encounter the error `Host unresolved volumes is null` or `Exception while calling pre-restore on SCV….Error mounting cloned LUN as datastore…` This occurs when the SnapCenter VMware plug-in attempts to resignature the clone. Due to VMware restrictions, the SnapCenter VMware plug-in cannot control the automatic resignature value in advanced ESXi configurations.

:link-with-underscores: https://kb.netapp.com/@api/deki/files/83736/1086826_-_SCV_clone_or_restores_fail_with_error_%27Host_Unresolved_volumes_is_null%27.pdf
For more information about the error, see {link-with-underscores}[KB article: SCV clone or restores fail with error 'Host Unresolved volumes is null^].
