---
sidebar: sidebar
permalink: scpivs44_download_the_ova_open_virtual_appliance.html
keywords:
summary: 'The .tar file includes OVA, which is a set of microservices for VM and datastore data protection and the certificate file.'
---

= Download the Open Virtual Appliance (OVA)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:21.861206
//

[.lead]
Before installing the Open Virtual Appliance (OVA), add the certificate to the vCenter. The .tar file contains the OVA and Entrust Root and Intermediate certificates, the certificates can be found within the certificates folder. The OVA deployment is supported in VMware vCenter 7u1 and above.

In VMware vCenter 7.0.3 versions and higher, the OVA signed by the Entrust certificate is no longer trusted. You need to perform the following procedure to resolve the issue.

.Steps
. To download the SnapCenter Plug-in for VMware:

* Log in to the NetApp Support Site ( https://mysupport.netapp.com/products/index.html[https://mysupport.netapp.com/products/index.html^]).
* From the list of products, select *SnapCenter Plug-in for VMware vSphere*, then select the *Download Latest Release* button.
* Download the SnapCenter Plug-in for VMware vSphere `.tar` file to any location.
. Extract the contents of the tar file. The tar file contains the OVA and certs folder. The certs folder contains the Entrust Root and Intermediate certificates.
. Log in with the vSphere Client to the vCenter Server.
. Navigate to *Administration > Certificates > Certificate Management*.
. Next to *Trusted Root certificates*, select *Add*
* Go to the _certs_ folder.
* Select the Entrust Root and Intermediate certificates.
* Install each certificate one at a time.
. The certificates are added to a panel under *Trusted Root Certificates*. 
Once the certificates are installed, OVA can be verified and deployed.

[NOTE]
If the downloaded OVA is not tampered, then the *Publisher* column displays 
*Trusted certificate*.