---
sidebar: sidebar
permalink: scpivs44_manage_the_vmware_vsphere_web_client_service.html
keywords:
summary: 'If the SnapCenter VMware vSphere client starts to behave incorrectly, you might need to clear the browser cache. If the problem persists, then restart the VMware vSphere client service.'
---

= Restart the VMware vSphere client service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:27.991697
//

[.lead]
If the SnapCenter VMware vSphere client starts to behave incorrectly, you might need to clear the browser cache. If the problem persists, then restart the VMware vSphere client service.

== Restart the web client service in a Linux vCenter

If your vCenter is on a Linux appliance, then you must use Linux commands to restart the SnapCenter VMware vSphere client service.

.Before you begin

You must be running vCenter 6.5 or later.

.Steps

. Use SSH to log in to the vCenter Server Appliance as root.
. Access the Appliance Shell or BASH Shell by using the following command:
+
`shell`

. Stop the web client service by using the following HTML5 command:
+
`service-control --stop vsphere-ui`

. Delete all stale scvm packages on vCenter by using the following HTML5 command:
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/rm -rf com.netapp.scv.client-<version_number>`
+
[IMPORTANT]
Do not remove the VASA or VSC7.x and later packages.

. Start the web client service by using the following HTML5 command:
+
`service-control --start vsphere-ui`
