---
sidebar: sidebar
permalink: scpivs44_restore_guest_files_and_folders_overview.html
keywords:
summary: 'You can restore files or folders from a virtual machine disk (VMDK) on a Windows guest OS.'
---

= Workflow, prerequisites, and limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can restore files or folders from a virtual machine disk (VMDK) on a Windows guest OS.

== Guest restore workflow

Guest OS restore operations include the following steps:

. Attach
+
Attach a virtual disk to a guest VM or proxy VM and start a guest file restore session.

. Wait
+
Wait for the attach operation to complete before you can browse and restore. When the attach
+
operation finishes, a guest file restore session is automatically created and an email notification is
+
sent.

. Select files or folders
+
Browse the VMDK in the Guest File Restore session and select one or more files or folders to restore.

. Restore
+
Restore the selected files or folders to a specified location.

== Prerequisites for restoring guest files and folders

Before you restore one or more files or folders from a VMDK on a Windows guest OS, you must be aware of all the requirements.

* VMware Tools must be installed and running.
+
SnapCenter uses information from VMware Tools to establish a connection to the VMware Guest OS.

* The Windows Guest OS must be running Windows Server 2008 R2 or later.
+
For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=105164;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^].

* Credentials for the target VM must specify the built-in domain administrator account or the built-in local administrator account. The username must be "Administrator." Before starting the restore operation, the credentials must be configured for the VM to which you want to attach the virtual disk. The credentials are required for both the attach operation and the subsequent restore operation. Workgroup users can use the built-in local administrator account.
+
[IMPORTANT]
If you must use an account that is not the built-in administrator account, but has administrative privileges within the VM, you must disable UAC on the guest VM.

* You must know the backup Snapshot copy and VMDK to restore from.
+
SnapCenter Plug-in for VMware vSphere does not support searching of files or folders to restore. Therefore, before you begin you must know the location of the files or folders with respect to the Snapshot copy and the corresponding VMDK.

* Virtual disk to be attached must be in a SnapCenter backup.
+
The virtual disk that contains the file or folder you want to restore must be in a VM backup that was performed using the virtual appliance for SnapCenter Plug-in for VMware vSphere.

* To use a proxy VM, the proxy VM must be configured.
+
If you want to attach a virtual disk to a proxy VM, the proxy VM must be configured before the attach and restore operation begins.

* For files with non-English-alphabet names, you must restore them in a directory, not as a single file.
+
You can restore files with non-alphabetic names, such as Japanese Kanji, by restoring the directory in which the files are located.

* Restoring from a Linux guest OS is not supported
+
You cannot restore files and folders from a VM that is running Linux guest OS. However, you can attach a VMDK and then manually restore the files and folders. For the latest information on supported guest OS, see the https://imt.netapp.com/matrix/imt.jsp?components=105164;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^].

== Guest file restore limitations

Before you restore a file or folder from a guest OS, you should be aware of what the feature does not support.

* You cannot restore dynamic disk types inside a guest OS.
* If you restore an encrypted file or folder, the encryption attribute is not retained. You cannot restore files or folders to an encrypted folder.
* The Guest File Browse page displays the hidden files and folder, which you cannot filter.
* You cannot restore from a Linux guest OS.
+
You cannot restore files and folders from a VM that is running Linux guest OS. However, you can attach a VMDK and then manually restore the files and folders. For the latest information on supported guest OS, see the https://imt.netapp.com/matrix/imt.jsp?components=105164;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^].

* You cannot restore from a NTFS file system to a FAT file system.
+
When you try to restore from NTFS-format to FAT-format, the NTFS security descriptor is not copied because the FAT file system does not support Windows security attributes.

* You cannot restore guest files from a cloned VMDK or an uninitialized VMDK.
* You cannot restore from secondary backups if the backup was performed on a system running ONTAP 9.2 or later and if the VMware consistency option was on.
* You cannot restore the directory structure for a file.
+
If a file in a nested directory is selected to be restored, the file is not restored with the same directory structure. The directory tree is not restored, only the file. If you want to restore a directory tree, you can copy the directory itself at the top of the structure.

* You cannot restore guest files from a vVol VM to an alternate host.

* You cannot restore encrypted guest files.
//Burt 1416895  23Nov2021 Ronya
