---
sidebar: sidebar
permalink: scpivs44_concepts_overview.html
keywords:
summary: 'SnapCenter Plug-in for VMware vSphere is a standalone virtual appliance (Open Virtual Appliance format) that provides data protection services for VMs and datastores, and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.'
---

= Product overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
[.lead]
SnapCenter Plug-in for VMware vSphere is a standalone virtual appliance (Open Virtual Appliance format) that provides data protection services for VMs and datastores, and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.

SnapCenter Plug-in for VMware vSphere is deployed as a Linux-based virtual appliance.

SnapCenter Plug-in for VMware vSphere adds the following functionality to your environment:

* Support for VM-consistent and crash-consistent data protection operations.
+
You can use the VMware vSphere client GUI in vCenter for all backup and restore operations of VMware virtual machines (traditional VMs and vVol VMs), VMDKs, and datastores. For vVol VMs (VMs in vVol datastores), only crash-consistent backups are supported. You can also restore VMs and VMDKs and restore files and folders that reside on a guest OS.
+
When backing up VMs, VMDKs, and datastores, the plug-in does not support RDMs. Backup jobs for VMs ignore RDMs. If you need to back up RDMs, you must use a SnapCenter application-based plug-in.
+
SnapCenter Plug-in for VMware vSphere includes a MySQL database that contains the SnapCenter Plug-in for VMware vSphere metadata. For VM-consistent and crash-consistent data protection, you do not need to install SnapCenter Server.

* Support for application-consistent (application over VMDK/RDM) data protection operations.
+
You can use the SnapCenter GUI and the appropriate SnapCenter application plug-ins for all backup and restore operations of databases and filesystems on primary and secondary storage on VMs.
+
SnapCenter natively leverages the SnapCenter Plug-in for VMware vSphere for all data protection operations on VMDKs, raw device mappings (RDMs), and NFS datastores. After the virtual appliance is deployed, the plug-in handles all interactions with vCenter. SnapCenter Plug-in for VMware vSphere supports all SnapCenter application-based plug-ins.
+
SnapCenter does not support single Snapshots of databases and VMs together. Backups for VMs and databases must be scheduled and run independently, which creates separate Snapshots, even if the databases and VMs are hosted in the same volume. Schedule the database application backups using the SnapCenter GUI; schedule the VM and datastore backups using the VMware vSphere client GUI.

* VMware tools is required for VM consistent Snapshots
+
If VMware tools is not installed and running, the file system is not quiesced and a crash-consistent Snapshot is created.

* VMware Storage vMotion is required for restore operations in SAN (VMFS)  environments
+
The restore workflow for VMware file system (VMFS) utilizes the VMware Storage vMotion feature. Storage vMotion is a part of the vSphere Standard License but is not available with the vSphere Essentials or Essentials Plus licenses.
+
Most restore operations in NFS environments use native ONTAP functionality (for example, Single File SnapRestore) and do not require VMware Storage vMotion.

* ONTAP tools for VMware vSphere is required to configure VMware vVol VMs.
+
You use ONTAP tools to provision and configure storage for vVols in ONTAP and in the VMware web client.
+
For more information, refer to the ONTAP tools for VMware vSphere documentation. Additionally, refer to https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] for latest information about the supported versions on ONTAP tools.

* SnapCenter Plug-in for VMware vSphere is deployed as a virtual appliance in a Linux VM
+
Although the virtual appliance must be installed as a Linux VM, the SnapCenter Plug-in for VMware vSphere supports both Windows-based and Linux-based vCenters. SnapCenter natively uses this plug-in without user intervention to communicate with your vCenter to support SnapCenter application-based plug-ins that perform data protection operations on Windows and Linux virtualized applications.

In addition to these major features, the SnapCenter Plug-in for VMware vSphere also provides support for iSCSI, Fiber Channel, FCoE, NFS 3.0/4.1, VMFS 5.0/6.0, NVMe over FC, and NVMe over TCP.

For the latest information about supported versions, refer to https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] (IMT).
// link to be changed

For information about NFS protocols and ESXi host, refer to the vSphere Storage documentation that is provided by VMware.

For information about SnapCenter data protection, refer to data protection information for your SnapCenter plug-in in the http://docs.netapp.com/us-en/snapcenter/index.html[SnapCenter Documentation^].

For information about supported upgrade and migration paths, refer to link:scpivs44_release_notes.html[SnapCenter Plug-in for VMware vSphere Release Notes^].
