---
sidebar: sidebar
permalink: scpivs44_role_based_access_control.html
keywords:
summary: 'SnapCenter Plug-in for VMware vSphere provides an additional level of RBAC for managing virtualized resources. The plug-in supports both vCenter Server RBAC and Data ONTAP RBAC.'
---

= Role-Based Access Control (RBAC)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:20.235275
//
[.lead]
SnapCenter Plug-in for VMware vSphere provides an additional level of RBAC for managing virtualized resources. The plug-in supports both vCenter Server RBAC and Data ONTAP RBAC.

SnapCenter and ONTAP RBAC applies only to SnapCenter Server application-consistent (application over VMDK) jobs. If you use the SnapCenter VMware plug-in to support SnapCenter application-consistent jobs, you must assign the SnapCenterAdmin role; you cannot change the permissions of the SnapCenterAdmin role.

The SnapCenter VMware plug-in ships with predefined vCenter roles. You must use the vCenter GUI to add these roles to vCenter Active Directory users to perform SnapCenter operations.

You can create and modify roles and add resource access to users at any time. However, when you are setting up the SnapCenter VMware plug-in for the first time, you should at least add Active Directory users or groups to roles, and then add resource access to those users or groups.
