---
sidebar: sidebar
permalink: scpivs44_migrate_snapcenter_backup_metadata_to_the_virtual_appliance.html
keywords:
summary:
---

= Migrate Windows-based SnapCenter VMware backup metadata
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:28.964302
//

[.lead]
You use the SnapCenter Windows PowerShell cmdlets to migrate SnapCenter VM-consistent backup metadata and SnapCenter application-consistent for virtualized data backup metadata to the SnapCenter Plug-in for VMware vSphere virtual appliance.

.Steps

. Back up the MySQL database and then copy and move that backup to a different location to make sure it does not get deleted due to the retention policy.
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html[Back up the SnapCenter Plug-in for VMware vSphere MySQL database]

. Log on to the VMware vSphere web client and verify that no jobs are running.
. Log on to the SnapCenter GUI using the SnapCenter Admin username.
+
Do not use any other username to log in, even if that username has all permissions, because it might cause a migration error.

. In the Windows SnapCenter GUI left navigation pane, click *Settings*, then click the *Credential* tab, and then click *Add* to add credentials for the virtual appliance.
. Create the name of the Run As credential to be used in the `invoke-SCVOVAMigration `cmdlet.
+
[NOTE]
You must select Linux for the Authentication field.
+
This step adds the credentials that SnapCenter Server uses to access the virtual appliance during the migration.

. Open a Windows PowerShell window and run the following cmdlets:
+
`Open-SmConnection`
+
`invoke-SCVOVAMigration -SourceSCVHost <old-SCV-host-IP> -DestinationSCVOVAHost <new-appliance-IP> -OVACredential <appliance-credentials> -ByPassValidationCheck -Overwrite -ContinueMigrationOnStorageError -ScheduleOffsetTime <time-offset>`
// BURT 1378132 observation 71, March 2021 Ronya
+
For an overview of the migration workflow, see link:scpivs44_migration_overview.html#migration_workflow[Migration workflow]
+
[IMPORTANT]
The optional `-Overwrite` parameter enables faster migration for large environments. This parameter overwrites data in the MySQL database on the SnapCenter Plug-in for VMware vSphere host.
Do not use the `-Overwrite` parameter more than once. If your migration was a partial migration, using the `-Overwrite` parameter again might overwrite existing migrated data.
+
[NOTE]
Use the ScheduleOffsetTime parameter if the source SnapCenter host and the destination SnapCenter VMware virtual appliance host are in different time zones. The value can be a positive or negative time offset to adjust scheduled backup run times. Specify the time difference in the format hh: mm:ss; for example, 06:00:00, or -06:00:00 for a negative value.
