---
sidebar: sidebar
permalink: scpivs44_minimum_ontap_privileges_required.html
keywords:
summary: 'The minimum ONTAP privileges that are required vary according to the SnapCenter plug-ins you are using for data protection.'
---

= ONTAP privileges required
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:28.623680
//

[.lead]
The minimum ONTAP privileges that are required vary according to the SnapCenter plug-ins you are using for data protection.

== Minimum ONTAP privileges required

All SnapCenter plug-ins require the following minimum privileges.

|===
|All-access commands: Minimum privileges required for ONTAP 8.3 and later

|event generate-autosupport-log
|job history show
job stop
|lun
lun create
lun delete
lun igroup add
lun igroup create
lun igroup delete
lun igroup rename
lun igroup show
lun mapping add-reporting-nodes
lun mapping create
lun mapping delete
lun mapping remove-reporting-nodes
lun mapping show
lun modify
lun move-in-volume
lun offline
lun online
lun persistent-reservation clear
lun resize
lun serial
lun show
|snapmirror list-destinations
snapmirror policy add-rule
snapmirror policy modify-rule
snapmirror policy remove-rule
snapmirror policy show
snapmirror restore
snapmirror show
snapmirror show-history
snapmirror update
snapmirror update-ls-set
|Version
|volume clone create
volume clone show
volume clone split start
volume clone split stop
volume create
volume destroy
volume file clone create
volume file show-disk-usage
volume offline
volume online
volume modify
volume qtree create
volume qtree delete
volume qtree modify
volume qtree show
volume restrict
volume show
volume snapshot create
volume snapshot delete
volume snapshot modify
volume snapshot rename
volume snapshot restore
volume snapshot restore-file
volume snapshot show
volume unmount
|vserver cifs
vserver cifs share create
vserver cifs share delete
vserver cifs shadowcopy show
vserver cifs share show
vserver cifs show
vserver export-policy
vserver export-policy create
vserver export-policy delete
vserver export-policy rule create
vserver export-policy rule show
vserver export-policy show
vserver iscsi
vserver iscsi connection show
vserver show
network interface
network interface failover-groups
network interface show
|===

|===
|Read-only Commands: Minimum Privileges Required for ONTAP 8.3 and Later

|
vserver
|===

== Additional ONTAP information

* If you are running ONTAP 8.2.x:
+
You must login as `vsadmin` on the storage VM to have the appropriate privileges for SnapCenter Plug-in for VMware vSphere operations.

* If you are running ONTAP 8.3 and later:
+
You must login as `vsadmin` or with a role that has the minimum privileges listed in the tables above.
* You need to be the cluster admin to create and manage user roles. You can associate the users either with Cluster storage VM or with storage VM.