---
sidebar: sidebar
permalink: scpivs44_mount_a_backup.html
keywords:
summary: 'You can mount a traditional datastore from a backup if you want to access files in the backup. You can either mount the backup to the same ESXi host where the backup was created or to an alternate ESXi host that has the same type of VM and host configurations. You can mount a datastore multiple times on a host.'
---

= Mount a backup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

// This file was created with NDAC Version 2.0 (August 17, 2020)
// 2020-09-09 12:24:23.855703

[.lead]
You can mount a traditional datastore from a backup if you want to access files in the backup. You can either mount the backup to the same ESXi host where the backup was created or to an alternate ESXi host that has the same type of VM and host configurations. You can mount a datastore multiple times on a host.

You cannot mount a vVol datastore.

.Before you begin

* Ensure alternate ESXi host can connect to the storage
+
If you want to mount to an alternate ESXi host, you must ensure that the alternate ESXi host can connect to the storage and has the following:
** Same UID and GID as that of the original host
** Same virtual appliance for SnapCenter Plug-in for VMware vSphere version as that of original host

* Map storage initiators to ESXi
+
Ensure that the initiators for the storage system are mapped to the ESXi.

* Clean up stale LUNs
+
Because the ESXi can only discover one unique LUN per datastore, the operation will fail if it finds more than one. This can occur if you start a mount operation before a previous mount operation has finished, or if you manually clone LUNs, or if clones are not deleted from storage during an unmount operation. To avoid discovery of multiple clones, you should clean up all stale LUNs on the storage.

.About this task

A mount operation might fail if the storage tier of the FabricPool where the datastore is located is unavailable.

.Steps

. In the VMware vSphere web client, click *Menu* in the toolbar, and then select *Storage* from the drop-down list.
. Right-click a datastore and select *NetApp SnapCenter* in the drop-down list, and then select *Mount Backup* in the secondary drop-down list.
. On the *Mount Datastore* page, select a backup and a backup location (primary or secondary), and then click *Finish*.
//Updated for BURT 1378132 observation 29, March 2021 Madhulika
. Optional: To verify that the datastore is mounted, perform the following:
.. Click *Menu* in the toolbar, and then select *Storage* from the drop-down list.
.. The left Navigator pane displays the datastore you mounted at the top of the list.
+
If you perform an attach or mount operation on a SnapVault destination volume that is protected by SnapVault schedules and is running ONTAP 8.3, you might see an extra Snapshot copy listed in the attach or mount dialog screen. This occurs because the attach or mount operation clones the SnapVault destination volume and ONTAP updates the volume by creating a new Snapshot copy.
+
To prevent new Snapshot copies from being created when you clone the volume, turn off the ONTAP schedule for the SnapVault volume. Previously existing Snapshot copies are not deleted.
