---
sidebar: sidebar
permalink: scpivs44_restore_the_most_recent_backup_of_the_mysql_database.html
keywords:
summary: 'You can use the maintenance console to restore the most recent backup of the MySQL database (also called an NSM database) for the SnapCenter Plug-in for VMware vSphere.'
---

= Restore the most recent backup of the MySQL database
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:24.609456
//

[.lead]
You can use the maintenance console to restore the most recent backup of the MySQL database (also called an NSM database) for the SnapCenter Plug-in for VMware vSphere.

.Steps

. Open a maintenance console window.
+
link:scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#access-the-maintenance-console[Access the maintenance console].
. From the Main Menu, enter option *1) Application Configuration*.
. From the Application Configuration Menu, enter option *6) MySQL backup and restore*.
. From the MySQL Backup and Restore Configuration Menu, enter option *3) Restore MySQL backup*.
. At the prompt “Restore using the most recent backup,” enter *y*, and then press *Enter*.
+
The backup MySQL database is restored to its original location.
