---
sidebar: sidebar
permalink: scpivs44_download_job_logs.html
keywords:
summary: 'You can download the job logs from the Job Monitor tab on the Dashboard of the SnapCenter VMware vSphere client.'
---

= Download job logs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:22.248621
//

[.lead]
You can download the job logs from the Job Monitor tab on the Dashboard of the SnapCenter VMware vSphere client.

If you encounter unexpected behavior while using the VMware vSphere client, you can use the log files to identify the cause and resolve the problem.

[NOTE]
The default value for retaining job logs is 30 days; the default value for retaining jobs is 90 days. Job logs and jobs that are older than the configured retention are purged every six hours. You can use the Configuration `jobs/cleanup` REST APIs to modify how long jobs and job logs are retained. You cannot modify the purge schedule.
// Burt 1381872  March 2021 Ronya
// GitHub comment and info from Sachin. Oct 2021 Ronya

.Steps

. From the vCenter client shortcut page, select SnapCenter Plug-in for VMware vSphere (SCV). 
. In the left navigation pane of SCV,  select *Dashboard* > *Job Monitor*.
. Select the download icon in the Job Monitor title bar.
+
You might need to scroll to the right to see the icon.
+
You can also double-click a job to access the Job Details window and then select *Download Job Logs*.

.Result

Job logs are located on the Linux VM host where the SnapCenter Plug-in for VMware vSphere is deployed. The default job log location is `/var/log/netapp`.

If you tried to download job logs but the log file named in the error message has been deleted, you might encounter the following error: `HTTP ERROR 500 Problem accessing /export-scv-logs`. To correct this error, check the file access status and permissions for the file named in the error message and correct the access problem.
