---
sidebar: sidebar
permalink: scpivs44_restore_a_specific_backup_of_the_mysql_database.html
keywords:
summary: 'You can use the maintenance console to restore a specific backup of the MySQL database (also called an NSM database) for the SnapCenter Plug-in for VMware vSphere virtual appliance.'
---

= Restore a specific backup of the MySQL database
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:24.673525
//

[.lead]
You can use the maintenance console to restore a specific backup of the MySQL database (also called an NSM database) for the SnapCenter Plug-in for VMware vSphere virtual appliance.

.Steps

. Open a maintenance console window.
+
link:scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#access-the-maintenance-console[Access the maintenance console].
. From the Main Menu, enter option *1) Application Configuration*.
. From the Application Configuration Menu, enter option *6) MySQL backup and restore*.
. From the MySQL Backup and Restore Configuration Menu, enter option *2) List MySQL
backups*, and then make a note of the backup you want to restore.
. From the MySQL Backup and Restore Configuration Menu, enter option *3) Restore MySQL backup*.
. At the prompt “Restore using the most recent backup,” enter *n*.
. At the prompt “Backup to restore from,” enter the backup name, and then press *Enter*.
+
The selected backup MySQL database is restored to its original location.
