---
sidebar: sidebar
permalink: scpivs44_prerequisites_for_migration.html
keywords:
summary:
---

= Prerequisites for migration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:28.925485
//
* You must be running SnapCenter Server 4.2 or later.
* You must use Admin credentials.
* The SnapCenter Plug-in for VMware vSphere virtual appliance must be deployed with the SnapCenter VMware plug-in enabled and registered on vCenter.
* On the SnapCenter VMware plug-in dashboard, the status for SnapCenter Plug-in for VMware vSphere must be “connected.”
* You must have created a Linux type Run As credential using the account that was specified during the deployment of the SnapCenter VMware plug-in.
* All guest file restore sessions must be deleted.
* SnapCenter hosts must be configured with IP addresses, not fully qualified domain names (FQDN).
+
In a Linked Mode environment, you must migrate all linked nodes together.

* Names for storage VMs must resolve to management LIFs.If you added `etc` host entries for storage VM names in SnapCenter, you must verify that they are also resolvable from the virtual appliance.
