---
sidebar: sidebar
permalink: scpivs44_set_up_proxy_vms_for_restore_operations.html
keywords:
summary: 'If you want to use a proxy VM for attaching a virtual disk for guest file restore operations, you must set up the proxy VM before you begin the restore operation. Although you can set up a proxy VM at any time, it might be more convenient to set it up immediately after the plug-in deployment completes.'
---

= Set up proxy VMs for restore operations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you want to use a proxy VM for attaching a virtual disk for guest file restore operations, you must set up the proxy VM before you begin the restore operation. Although you can set up a proxy VM at any time, it might be more convenient to set it up immediately after the plug-in deployment completes.

.Steps

. From the vSphere client shortcuts window, select *SnapCenter Plug-in for VMware vSphere* under plug-ins.
. In the left navigation select *Guest File Restore*.
. In the *Run As Credentials* section, do one of the following:
+
|===
|To do this… |Do this…

|Use existing credentials
|Select any of the configured credentials.
|Add new credentials
a|
. Select *Add*.
. In the *Run As Credentials* dialog box, enter the credentials.
. Select *Select VM*, then select a VM in the *Proxy VM* dialog box. Select *Save* to return to the *Run As Credentials* dialog box.
. Enter the credentials.
For Username, you must enter “Administrator”.
|===
+
SnapCenter Plug-in for VMware vSphere uses the selected credentials to log into the selected proxy VM.
+
The Run As credentials must be the default domain administrator that is provided by Windows or the built-in local administrator. Workgroup users can use the built-in local administrator account.

. In the *Proxy Credentials* section, select *Add* to add a VM to use as a proxy.
. In the *Proxy VM* dialog box, complete the information, and then select *Save*.

[NOTE]
You need to delete the proxy VM from the SnapCenter Plug-in for VMware vSphere UI before you can delete it from ESXi host.
