---
sidebar: sidebar
permalink: scpivs44_manage_resource_groups.html
keywords:
summary: 'You can create, modify, and delete backup resource groups, and perform backup operations on resource groups.'
---

= Manage resource groups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:26.480882
//

[.lead]
You can create, modify, and delete backup resource groups, and perform backup operations on resource groups.

[NOTE]
Resource groups are called backup jobs in Virtual Storage Console (VSC).

== Suspend and resume operations on resource groups

Pause scheduled operations on a resource group. Enable them again when needed.

.Steps

. In the left navigator pane of the SCV plug-in, select *Resource Groups*, select a resource group and select *Suspend* (or select *Resume*).
. In the confirmation box, select *OK* to confirm.
// BURT 1378132 observation 44, March 2021 Ronya

.After you finish

On the Resource Groups page, the job status for the suspended resource is `Under_Maintenance`. You might need to scroll to the right of the table to see the Job Status column.

After backup operations are resumed, the Job Status changes to `Production`.

== Modify resource groups

You can remove or add resources in resource groups in vCenter, detach or attach policies, modify schedules, or modify any other resource group option.

.About this task

If you want to modify the name of a resource group, do not use the following special characters in VM, datastore, policy, backup, or resource group names:

% & * $ # @ ! \ / : * ? " < > - | ; ' , and space.
// SNAPDOC-359 updates
An underscore character (_) is allowed.

.Steps

. In the left navigator pane of the SCV plug-in, select *Resource Groups*, then select a resource group and select *Edit*.
. On the left list in the *Edit Resource Group* wizard, select the category that you want to modify and enter your changes.
+
You can make changes in multiple categories. You can also edit secondary protected resources in this option.
// 6.1 update

. Select *Next* until you see the Summary page, and then select *Finish*.

== Delete resource groups

Delete a resource group in vCenter if you do not need to protect the resources. Delete all resource groups before removing SnapCenter Plug-in for VMware vSphere.

.About this task

All resource group delete operations are performed as force deletes. When you delete a resource group, the system detaches all policies from the vCenter resource group, removes the resource group from SnapCenter Plug-in for VMware vSphere, and deletes all backups and snapshots of the resource group.

[NOTE]
In a SnapVault relationship, you cannot delete the last snapshot, therefore you cannot delete the resource group. Before deleting a resource group in a SnapVault relationship, use System Manager or ONTAP CLI to remove the relationship, then delete the last snapshot.

.Steps

. In the left navigator pane of the SCV plug-in, select *Resource Groups*, then select a resource group and select *Delete*.
. In the *Delete resource group* confirmation dialog, select *OK* to confirm. Deleting a resource group does not remove secondary protection. If needed, use System Manager to delete secondary protection. Consistency groups created for the resource group are not automatically removed; you must manually delete them from ONTAP using System Manager or another supported interface.
//SCV 6.2 updates
// BURT 1378132 observation 46, March 2021 Ronya
