---
sidebar: sidebar
permalink: scpivs44_restore_deleted_vms_from_backups.html
keywords:
summary: 'You can restore a deleted VM from a datastore primary or secondary backup to an ESXi host that you select.'
---

= Restore deleted VMs from backups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can restore a deleted VM from a datastore primary or secondary backup to an ESXi host that you select.

You can restore VMs to the following locations:

* Restore to original location
** To the original datastore mounted on the original ESXi host (this makes a copy of the VM)

* Restore to alternate location
** To a different datastore mounted on the original ESXi host
** To the original datastore mounted on a different ESXi host that is managed by the same vCenter
** To a different datastore mounted on a different ESXi host that is managed by the same vCenter
** To a different datastore mounted on a different ESXi host that is managed by a different vCenter in linked mode

[NOTE]
When restoring to a different location, SnapCenter Plug-in for VMware vSphere must be running in the linked vCenter that is the destination for the restore operation. The destination datastore must have sufficient space.
// Burt 1382316 March 2021 Ronya

[NOTE]
You cannot restore vVol VMs to an alternate location.

[NOTE]
When restoring a deleted VM, any tags or folders that were originally assigned to the VM are not restored.
// Burt 1427781 23Nov2021 Ronya

.Before you begin

* The user account for the storage system, on the Storage Systems page in the VMware vSphere web client, must have the link:scpivs44_minimum_ontap_privileges_required.html[Minimum ONTAP privileges required for ONTAP].

* The user account in vCenter must have the link:scpivs44_minimum_vcenter_privileges_required.html[Minimum vCenter privileges required for SnapCenter Plug-in for VMware vSphere].

* A backup must exist.
+
You must have created a backup of the VM using the SnapCenter Plug-in for VMware vSphere before you can restore the VMDKs on that VM.

[TIP]
For improved performance of restore operations in NFS environments, enable the VMware application vStorage API for Array Integration (VAAI).
//Burt 1377556 Mar2021 Ronya

.About this task

You cannot restore a datastore, but you can restore any VM in the datastore.

A restore operation might fail if the storage tier of the FabricPool where the VM is located is unavailable.

.Steps

. Click *Menu* and select the *Storage* menu option, then select a datastore, then select the *Configure* tab, and then click *Backups* in the *SnapCenter Plug-in for VMware vSphere* section.
. Double-click on a backup to see a list of all VMs that are included in the backup.
. Select the deleted VM from the backup list and click *Restore*.
. In the *Restore* wizard, on the *Select Backup* page, select the backup copy that you want to restore from.
+
You can search for a specific backup name or a partial backup name, or you can filter the backup list by clicking the filter icon and selecting a date and time range, selecting whether you want backups that contain VMware Snapshots, whether you want mounted backups, and the location. Click *OK* to return to the wizard.

. On the *Select Scope* page, select *Entire virtual machine* in the *Restore scope* field, then select the restore location, and then enter the Destination ESXi information where the backup should be mounted.
+
The restore destination can be any ESXi host that has been added to SnapCenter. This option restores the contents of the selected backup in which the VM resided from a Snapshot copy with the specified time and date. The *Restart VM* check box is checked if you select this option and the VM will be powered on.
// BURT 1378132 observation 31, March 2021 Ronya
+
If you are restoring a VM in an NFS datastore onto an alternate ESXi host that is in an ESXi cluster, then after the VM is restored, it is registered on the alternate host.


. On the *Select Location* page, select the location of the backup that you want to restore from (primary or secondary).
// BURT 1378132 observation 32, March 2021 Ronya
. Review the Summary page and then click *Finish*.
