---
sidebar: sidebar
permalink: scpivs44_restore_vms_from_backups.html
keywords:
summary: 'When you restore a VM, you can overwrite the existing content with the backup copy that you select or you can make a copy of the VM.'
---

= Restore VMs from backups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)


[.lead]
When you restore a VM, you can overwrite the existing content with the backup copy that you select or you can make a copy of the VM.

You can restore VMs to the following locations:

* Restore to original location

** To the original datastore mounted on the original ESXi host (this overwrites the original VM)

* Restore to alternate location
** To a different datastore mounted on the original ESXi host
** To the original datastore mounted on a different ESXi host that is managed by the same vCenter
** To a different datastore mounted on a different ESXi host that is managed by the same vCenter
** To a different datastore mounted on a different ESXi host that is managed by a different vCenter in linked mode

[NOTE]
You cannot restore vVol VMs to an alternate host.

[NOTE]
The following restore workflow is not supported: Add a storage VM, then perform a backup of that VM, then delete the storage VM and add a cluster that includes that same storage VM, and then attempt to restore the original backup.

[TIP]
For improved performance of restore operations in NFS environments, enable the VMware application vStorage API for Array Integration (VAAI).
//Burt 1377556 Mar2021 Ronya

.Before you begin

* A backup must exist.
+
You must have created a backup of the VM using the SnapCenter VMware plug-in before you can restore the VM.
+
[NOTE]
Restore operations cannot finish successfully if there are Snapshot copies of the VM that were performed by software other than the SnapCenter Plug-in for VMware vSphere.

* The destination datastore must be ready.
+
** The destination datastore for the restore operation must have enough space to accommodate a copy of all the VM files (for example: vmdk, vmx, vmsd).
+
** The destination datastore must not contain stale VM files from previous restore operation failures. Stale files have the name format `restore_xxx_xxxxxx_<filename>`.

* The VM must not be in transit.
+
The VM that you want to restore must not be in a state of vMotion or Storage vMotion.

* HA configuration errors
+
Ensure there are no HA configuration errors displayed on the vCenter ESXi Host Summary screen before restoring backups to a different location.

* Restoring to a different locations
+
** When restoring to a different location, SnapCenter Plug-in for VMware vSphere must be running in the vCenter that is the destination for the restore operation. The destination datastore must have sufficient space.
//Burt 1382316 March 2021 Ronya
+
** The destination vCenter in the Restore To alternate Location field must be DNS resolvable.
//Burt 14881870 June 2022 Ronya

.About this task

* VM is unregistered and registered again
+
The restore operation for VMs unregisters the original VM, restores the VM from a backup Snapshot copy, and registers the restored VM with the same name and configuration on the same ESXi server. You must manually add the VMs to resource groups after the restore.

* Restoring datastores
+
You cannot restore a datastore, but you can restore any VM in the datastore.

* Restoring vVol VMs
** vVol datastores that span VMs are not supported. Because attached VMDKs in a VM-spanning vVol datastore are not backed up, the restored VMs will contain only partial VMDKs.
** You cannot restore a vVol to an alternate host.
** vVol automatic rebalance is not supported.

* VMware consistency snapshot failures for a VM
+
Even if a VMware consistency snapshot for a VM fails, the VM is nevertheless backed up. You can view the entities contained in the backup copy in the Restore wizard and use it for restore operations.

* A restore operation might fail if the storage tier of the FabricPool where the VM is located is unavailable.

.Steps

. In the VMware vSphere web client GUI, click *Menu* in the toolbar, and then select *VMs and Templates* from the drop-down list.
+
[NOTE]
If you are restoring a deleted VM, the storage VM credentials that were added to the SnapCenter VMware plug-in must be `vsadmin` or a user account that has all the same privileges as `vsadmin`. The host must be on a storage system that is running ONTAP 8.2.2 or later.

. In the left Navigator pane, right-click a VM, then select *NetApp SnapCenter* in the drop-down list, and then select *Restore* in the secondary drop-down list to start the wizard.
. In the *Restore* wizard, on the *Select Backup* page, select the backup Snapshot copy that you want to restore.
+
You can search for a specific backup name or a partial backup name, or you can filter the backup list by clicking the filter icon and selecting a date and time range, selecting whether you want backups that contain VMware Snapshots, whether you want mounted backups, and the location.  Click *OK* to return to the wizard.

. On the *Select Scope* page, select *Entire virtual machine* in the *Restore scope* field, then select the restore location, and then enter the destination information where the backup should be mounted.
+
In the *VM name* field, if the same VM name exists, then the new VM name format is `<vm_name>_<timestamp>`.
// Review comments from QA  Arpil2021  Ronya
+
When restoring partial backups, the restore operation skips the *Select Scope* page.
//Burt 1371420 March 2021  Ronya

. On the *Select Location* page, select the location for the restored datastore.
+
In SnapCenter Plug-in for VMware vSphere 4.5 and later, you can select secondary storage for FlexGroup volumes.

. Review the Summary page and then click *Finish*.
. Optional: Monitor the operation progress by clicking *Recent Tasks* at the bottom of the screen.
+
Refresh the screen to display updated information.

.After you finish

* Change IP address
+
If you restored to a different location, then you must change the IP address of the newly created VM to avoid an IP address conflict when static IP addresses are configured.

* Add restored VMs to resource groups
+
Although the VMs are restored, they are not automatically added to their former resource groups. Therefore, you must manually add the restored VMs to the appropriate resource groups.
