---
sidebar: sidebar
permalink: scpivs48_rest_apis_audit_logs.html
keywords:
summary: 'REST APIs to generate audit logs'
---

= REST APIs to generate audit logs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can collect the audit log details from swagger rest APIs as well as the SCV plugin user interface.

Given below are the swagger rest APIs:

1.	GET 4.1/audit/logs: Get audit data for all logs
2.	GET 4.1/audit/logs/{filename}: Get audit data for a specific log file
3.	POST 4.1/audit/verify: Trigger audit log verification.
4.  GET /4.1/audit/config: Get the audit and syslog server config
5.  PUT /4.1/audit/config: Update the audit and syslog server config

To generate audit logs for VMware vSphere client jobs using the SnapCenter Plug-in for VMware vSphere REST APIs, you must use the REST API calls for VMware vSphere.

For each REST API, add `https://<server>:<port>/api` at the front of the REST API to form a complete endpoint.

Use the following REST APIs in the Jobs section to get detailed information on jobs:

|===
|REST API |Comments

|`4.1/audit/logs`
|returns audit log files with integrity data
|`4.1/audit/logs/{filename}`
|get specific audit log file with integrity data
|`4.1/audit/verify`
|triggers audit verification
|`4.1/audit/syslogcert`
|updates the syslog server certificate 
|===
