---
sidebar: sidebar
permalink: scpivs44_download_the_ova_open_virtual_appliance.html
keywords:
summary: 'The .tar file includes OVA, which is a set of microservices for VM and datastore data protection and the certificate file.'
---

= Download the Open Virtual Appliance(OVA)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:21.861206
//

[.lead]
Before installing the OVA, you need to add certificate to the VMware Certificate Store. The SCV OVA is packaged as a TAR that contains the OVA file, certificates combined into a single PEM file, and instructions on how to add the certificate to the vCenter. The OVA deployment is supported in VMware vCenter 7u1 and above.

[IMPORTANT]
In VMware vCenter 7.0.3 versions and higher, the OVA signed by the Entrust certificate is no longer trusted. 
// is this required?

.Steps
. Log in with the vSphere Client to the vCenter Server.
. Navigate to *Administration > Certificates > Certificate Management*.
. Next to *Trusted Root Store*, click *Add*
. Browse for the AD FS root certificate and click *Add*
The certificate is added in a panel under *Trusted Root Certificates*.
Once the certificates are installed, OVA can be verified and deployed.
. To download the SnapCenter Plug-in for VMware:

* Log in to the NetApp Support Site ( https://mysupport.netapp.com/products/index.html[https://mysupport.netapp.com/products/index.html^]).
* From the list of products, select *SnapCenter Plug-in for VMware vSphere*, then click the *Download Latest Release* button.
* Download the SnapCenter Plug-in for VMware vSphere `.tar` file to any location.

[NOTE]
If the downloaded OVA is not tampered, then the *Publisher* column displays 
*Trusted certificate*.