---
sidebar: sidebar
permalink: scpivs44_log_in_to_the_snapcenter_vmware_vsphere_web_client.html
keywords:
summary: 'When SnapCenter Plug-in for VMware vSphere is deployed, it installs a VMware vSphere client on vCenter, which is displayed on the vCenter screen with other vSphere clients.'
---

= Log in to the SnapCenter VMware vSphere client
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-09 12:24:21.767331
//

[.lead]
When SnapCenter Plug-in for VMware vSphere is deployed, it installs a VMware vSphere client on vCenter, which is displayed on the vCenter screen with other vSphere clients.

.Before you begin

Transport Layer Security (TLS) must be enabled in vCenter. Refer to the VMware documentation.

.Steps

. In your browser, navigate to VMware vSphere vCenter.
. Log in to the *VMware vCenter Single Sign-On* page.
+
[IMPORTANT]
Click the *Login* button. Due to a known VMware issue, do not use the ENTER key to log in. For details, refer to VMware documentation on ESXi Embedded Host Client issues.

. On the *VMware vSphere client* page, click Menu in the toolbar, and then select *SnapCenter Plug-in for VMware vSphere*.
