---
permalink: scv60_releasenotes_whats_new.html
sidebar: sidebar
keywords: what's new, release notes, scv, 6.0, 6.0.1
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.0."
---

= What's new

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
SnapCenter Plug-in for VMware vSphere 6.0 release enables support for key ONTAP features like NVMe over TCP protocol and SnapMirror active sync.

[NOTE]
====
For the latest information about supported versions, refer to NetApp Interoperability Matrix Tool (http://mysupport.netapp.com/matrix[IMT^]).
====

== SnapCenter Plug-in for VMware vSphere 6.0.1

[cols="30%,70%",options="header"]
|===
| Update | Description
a|
NVME over FC protocol support
a|
SnapCenter plug-in for VMware vSphere 6.0.1 release supports NVMe over FC protocol for VMFS datastores.
a|
ONTAP tools for VMware vSphere 10.x integration
a|
ONTAP tools for VMware vSphere 10.x helps to configure VMware vVol virtual machines. Beginning with SnapCenter plug-in for VMware vSphere 6.0.1 release, backup and restore operations of virtual machines residing on NFS based vVols datastore is supported.
|===

== SnapCenter Plug-in for VMware vSphere 6.0

[cols="30%,70%",options="header"]
|===
| Update | Description
a|
NVMe over TCP protocol support
a|
SnapCenter plug-in for VMware vSphere 6.0 release supports NVMe over TCP protocol for VMFS datastores.

NVMe over TCP does not require any special hardware to deploy. Like iSCSI, NVMe/TCP can use any ethernet NICs and switches, making it simpler and less expensive to deploy and maintain.

VMFS datastores with NVMe over TCP protocol support all operations that iSCSI based VMFS datastores support, like the backup, restore, mount, attach, and detach operations.

The minimum software requirements for NVMe over TCP protocol support are:

* vCenter vSphere 7.0U3
* ESXi host 7.0U3
* ONTAP 9.10.1
a|
SnapMirror active sync
a|
SnapCenter Plug-in for VMware vSphere enables you to leverage the capabilities of SnapMirror active sync like zero Recovery Point Objective (RPO) and Recovery Time Objective (RTO), and Transparent Application Failover. Business continuity for SAN applications enables you to backup and recover applications and virtual machines on SnapMirror active sync using SnapCenter Plug-in for VMware vSphere.

SnapMirror active sync is supported only for VMFS Datastores.
a|
SnapCenter Plug-in for VMware vSphere with vCenter Server
a|
The registration of SnapCenter Plug-in for VMware vSphere with vCenter Server using 8144 port is removed. It is recommended that you use APIs (Swagger-UI) for vCenter registration and unregistration actions.
|===