---
permalink: scv60_releasenotes_60_whats_new.html
sidebar: sidebar
keywords: what's new, release notes, scv, 6.0, 6.0.1
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.0."
---

= What's new in SnapCenter Plug-in for VMware vSphere 6.0

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
[cols="30%,70%",options="header"]
|===
| Update | Description
a|
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_concepts_overview.html[Support for NVMe over TCP protocol]
a|
SnapCenter Plug-in for VMware vSphere 6.0 now supports NVMe over TCP protocol for VMFS datastores.

You don't need any additional hardware to deploy NVMe over TCP protocol, which makes it simpler and cost-effective for you.

Like iSCSI, VMFS datastores with NVMe over TCP protocol can use any ethernet NICs and switches, and support all standard operations, such as backup, restore, mount, attach, and detach.
a|
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies_for_vms_and_datastores.html[Support for SnapMirror active sync]
a|
You can now use SnapCenter Plug-in for VMware vSphere to configure SnapMirror active sync features, such as zero Recovery Point Objective (RPO), Recovery Time Objective (RTO), and Transparent Application Failover.

SnapMirror active sync is supported for only VMFS datastores. 
|===