---
permalink: scv_releasenotes_whats_new.html
sidebar: sidebar
keywords: what's new, release notes, scv, 6.2
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2."
---

= What's new in the SnapCenter Plug-in for VMware vSphere 6.2

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2.

The SnapCenter Plug-in for VMware vSphere 6.2 release adds support for backup and recovery of virtual machines (VMs) on VMFS datastores for ASA r2 systems running ONTAP 9.17.1 or later.
With this release, you can perform the following operations for VMs, datastores, and Virtual Machine Disk (VMDK) format on ASA r2 systems:

* Provision consistency groups for primary protection
* Perform consistency group-based backups
* Use hierarchical consistency groups (available with ONTAP 9.17.1 and later versions)
* Run clone workflows
* Perform restore workflows
* Provision secondary protection when creating or modifying resource groups (available with ONTAP 9.16.1 and later versions)

Beginning with this release, SnapCenter Plug-in for VMware vSphere supports Amazon FSxN for NetApp ONTAP storage systems running version 9.10 or later.

[NOTE]
====
You can now perform seamless, one click, non-disruptive migration from SnapCenter Plug-in for VMware to NetApp Backup and Recovery. NetApp Backup and Recovery provides enhanced data protection and management capabilities, including:

* Support for the 3-2-1 backup and archival strategy
* Ransomware protection with SnapLock and logical air-gapped backups using object locking
* Automated remediation during ransomware scans
* Automated SnapMirror relationship creation for secondary and object storage targets, streamlined backup retention management, and simplified application and VM backup workflows
* Improved scalability and performance to accommodate growing data volumes
* Reduced overhead and total cost of ownership with a fully managed backup service
* Centralized backup management of datastore and VMs across multiple vCenter instances from a single interface
* Quick restore of file and folder from Windows and Linux guest OS
====
// * Disaster recovery enablement with alternate location restore
Refer to the following links for more information:

* https://docs.netapp.com/us-en/data-services-backup-recovery/[NetApp Backup and Recovery documentation].
* https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-discovery.html[Discover VMware workloads with NetApp Backup and Recovery]
* https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-login.html[Log in to NetApp Backup and Recovery]
* https://console.netapp.com/unified-backup-restore[Access NetApp Backup and Recovery service]

== Protect your VMware estate using NetApp Backup and Recovery

video::UeT9yFssTug[youtube, width=848, height=480]

// video::protect-your-vmware-estate-using-netapp-backup-and-recovery[uet9yfsstug, title="Protect your VMware estate using NetApp Backup and Recovery"]


// video::096e1740-d115-44cf-8c27-b051011611eb[panopto, title="Subscribe to the Console from the AWS marketplace"]

// You cannot embed a NetApp video directly in AsciiDoc using the video:: macro, because it only supports local video files or certain platforms (like YouTube, Vimeo, Panopto). The NetApp video portal is not supported.

// patch update for SCV 6.2 P1
