---
permalink: scv_releasenotes_whats_new.html
sidebar: sidebar
keywords: what's new, release notes, scv, 6.2
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2."
---

= What's new in the SnapCenter Plug-in for VMware vSphere 6.2

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2.

The SnapCenter Plug-in for VMware vSphere 6.2 release adds support for backup and recovery of virtual machines (VMs) on VMFS datastores for ASA r2 systems running ONTAP 9.17.1 or later.
With this release, you can perform the following operations for VMs, datastores, and Virtual Machine Disk (VMDK) format on ASA r2 systems:

* Provision consistency groups for primary protection
* Perform consistency group-based backups
* Use hierarchical consistency groups (available with ONTAP 9.17.1 and later versions)
* Run clone workflows
* Perform restore workflows
* Provision secondary protection when creating or modifying resource groups (available with ONTAP 9.16.1 and later versions)

SnapCenter Plug-in for VMware vSphere 6.2 introduces integration with NetApp Backup and Recovery (NBR), delivering enhanced data protection and management capabilities:

* Support for the 3-2-1 backup and archival strategy
* Ransomware protection with SnapLock and logical air-gapped backups using object locking
* Automated remediation during ransomware scans
* Disaster recovery enablement with alternate location restore
* Automated SnapMirror relationship creation for secondary and object storage targets, streamlined backup retention management, and simplified application and VM backup workflows
* Improved scalability and performance to accommodate growing data volumes
* Reduced overhead and total cost of ownership with a fully managed backup service
* Centralized management of multiple vCenter instances from a single interface

Beginning with this release, SnapCenter Plug-in for VMware vSphere supports Amazon FSxN for NetApp ONTAP storage systems running version 9.10 or later.
// patch update for SCV 6.2 P1
