---
permalink: scv_releasenotes_whats_new.html
sidebar: sidebar
keywords: what's new, release notes, scv, 6.2
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2."
---

= What's new in SnapCenter Plug-in for VMware vSphere 6.2

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.2.

The SnapCenter Plug-in for VMware vSphere 6.2 release adds support for backup and recovery of virtual machines (VMs) on VMFS datastores using ONTAP 9.17.1 for ASA r2 systems.
With this release, you can perform the following operations for VMs, datastores, and Virtual Machine Disk (VMDK) format on ASA r2 systems:

* Provision consistency groups for primary protection
* Perform consistency group-based backups
* Use hierarchical consistency groups (available with ONTAP 9.17.1 and later versions)
* Run clone workflows
* Perform restore workflows
* Provision secondary protection when creating or modifying resource groups (available with ONTAP 9.16.1 and later versions)

