---
permalink: scv_rn_upgrade_paths.html
sidebar: sidebar
keywords: upgrade paths, scv, 6.1
summary: "Learn about the new capabilities available in SnapCenter Plug-in for VMware vSphere 6.1."
---

= Upgrade paths

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The version of SnapCenter Plug-in for VMware vSphere (SCV) that you can upgrade to depends on the version that you're currently running. 

[NOTE]
====
Upgrade to SnapCenter Plug-in for VMware vSphere (SCV) 4.8 and above is supported only on VMware vCenter server 7 update 1 and later versions. For VMware vCenter server prior to version 7 update 1, you should continue to use SCV 4.7. 
====

[cols="50%,50%",options="header"]
|===
| If you are on SCV version… | You can directly upgrade SCV to…
a|
SCV 6.0
a|
SCV 6.1
a|
SCV 5.0
a|
SCV 6.0 and SCV 6.1
a|
SCV 4.9
a|
SCV 5.0 and SCV 6.0
a|
SCV 4.8
a|
SCV 4.9 and SCV 5.0
a|
SCV 4.7
a|
SCV 4.8 and SCV 4.9
|===

For virtualized databases and file systems that are integrated with SnapCenter, this is the upgrade path: 
[cols="30%,30%,40%",options="header"]
|===
| If you are using | If your VMware plug-in is… | You can directly upgrade to…
a|
SnapCenter 6.1
a|
SCV 6.0
a|
SCV 6.1
a|
SnapCenter 6.0
a|
SCV 5.0
a|
SCV 6.0
a|
SnapCenter 5.0
a|
SCV 4.9
a|
SCV 5.0
a|
SnapCenter 4.9
a|
SCV 4.8
a|
SCV 4.9
a|
SnapCenter 4.8
a|
SCV 4.7
a|
SCV 4.8
|===

For the latest information about supported versions, refer to https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] (IMT).
